# Generated by Django 4.1.7 on 2023-03-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mFarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='sacco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mFarm.sacco'),
        ),
    ]
