# Generated by Django 4.2 on 2023-04-05 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mFarm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milkevaluation',
            name='gross_price',
        ),
        migrations.RemoveField(
            model_name='milkevaluation',
            name='quantity_supplied',
        ),
    ]
