# Generated by Django 4.1.7 on 2023-03-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mFarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
