# Generated by Django 4.1.7 on 2023-03-16 11:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mFarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacco',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sacco',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE'),
        ),
    ]
