# Generated by Django 4.1.7 on 2023-03-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mFarm', '0002_milkstatus_alter_farmer_email_milk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milkstatus',
            name='spoilt',
        ),
        migrations.AlterField(
            model_name='milkstatus',
            name='fresh',
            field=models.BooleanField(default=False),
        ),
    ]
