# Generated by Django 4.2 on 2023-04-05 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mFarm', '0002_remove_milkevaluation_gross_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milk',
            name='dateCollected',
            field=models.DateTimeField(auto_created=True, default=datetime.date(2023, 4, 5)),
        ),
    ]
