# Generated by Django 4.1.7 on 2023-03-09 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mFarm', '0002_remove_milkcollection_quantitycollected'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostEvaluator',
            fields=[
                ('milkevaluation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mFarm.milkevaluation')),
            ],
            bases=('mFarm.milkevaluation',),
        ),
        migrations.AddField(
            model_name='milkevaluation',
            name='gross_price',
            field=models.FloatField(default=12.0),
        ),
        migrations.AlterField(
            model_name='milkevaluation',
            name='butter_fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='milkevaluation',
            name='protein_content',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='milkevaluation',
            name='quantity_supplied',
            field=models.FloatField(),
        ),
    ]
