# Generated by Django 4.1.7 on 2023-03-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mFarm', '0003_remove_milkstatus_spoilt_alter_milkstatus_fresh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milkstatus',
            name='fresh',
        ),
        migrations.AddField(
            model_name='milkstatus',
            name='status',
            field=models.CharField(choices=[('fresh', 'Fresh'), ('spoilt', 'Spoilt')], default='fresh', max_length=7),
        ),
    ]
