# Generated by Django 4.1.7 on 2023-03-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mFarm', '0003_costevaluator_milkevaluation_gross_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkevaluation',
            name='gross_price',
            field=models.FloatField(),
        ),
    ]
