# Generated by Django 4.1.7 on 2023-03-08 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mFarm', '0004_remove_milkstatus_fresh_milkstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milk',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='MilkCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCollected', models.DateTimeField(auto_now_add=True)),
                ('farmerCollected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mFarm.farmer')),
                ('milk_collected', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mFarm.milk')),
            ],
        ),
    ]
