# Generated by Django 4.1.7 on 2023-03-08 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mFarm', '0004_remove_milkstatus_fresh_milkstatus_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('butter_fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein_content', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_supplied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('the_milk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mFarm.milk')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_period', models.DateField()),
                ('amount', models.FloatField()),
                ('quantity', models.FloatField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mFarm.farmer')),
            ],
        ),
    ]
