# Generated by Django 4.1.7 on 2023-03-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mFarm', '0005_alter_milk_quantity_milkcollection'),
        ('mFarm', '0005_milkevaluation_billing'),
    ]

    operations = [
    ]
