# Generated by Django 4.1.7 on 2023-03-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mFarm', '0006_merge_20230308_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milkcollection',
            name='milk_collected',
        ),
        migrations.AlterField(
            model_name='milk',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
